mental_mutation_list = {
    range(1, 3): {"name": "Absorption", "kind": "combat", "function": Absorption},
    range(3, 4): {
        "name": "Alternate Banishment",
        "kind": "combat",
        "function": AlternateBanishment,
    },
    range(4, 6): {
        "name": "Animal Attachment",
        "kind": "combat",
        "function": AnimalAttachment,
    },
    range(6, 8): {
        "name": "Calculations",
        "kind": "combat",
        "function": Calculations,
    },
    range(8, 10): {
        "name": "Communicate",
        "kind": "combat",
        "function": Communicate,
    },
    range(10, 11): {
        "name": "Cryokinesis",
        "kind": "combat",
        "function": Cryokinesis,
    },
    range(11, 12): {
        "name": "Death Field Generation",
        "kind": "combat",
        "function": DeathFieldGeneration,
    },
    range(12, 13): {
        "name": "Density Control",
        "kind": "combat",
        "function": DensityControl,
    },
    range(13, 15): {"name": "Detections", "kind": "combat", "function": Detections},
    range(15, 17): {
        "name": "Directional Sense",
        "kind": "combat",
        "function": DirectionalSense,
    },
    range(17, 18): {"name": "Empathy", "kind": "combat", "function": Empathy},
    range(18, 20): {
        "name": "Energy Attraction",
        "kind": "defect",
        "function": EnergyAttraction,
    },
    range(20, 21): {
        "name": "Epileptic Projection",
        "kind": "combat",
        "function": EpilepticProjection,
    },
    range(21, 22): {
        "name": "Extra Sensory Perception",
        "kind": "combat",
        "function": ExtraSensoryPerception,
    },
    range(22, 23): {
        "name": "Force Field Generation",
        "kind": "combat",
        "function": ForceFieldGeneration,
    },
    range(23, 24): {
        "name": "Gyrokinesis",
        "kind": "combat",
        "function": Gyrokinesis,
    },
    range(24, 26): {
        "name": "Heightened Brain Talent",
        "kind": "combat",
        "function": HeightenedBrainTalent,
    },
    range(26, 28): {
        "name": "Hostility Field Generation",
        "kind": "defect",
        "function": HostilityFieldGeneration,
    },
    range(28, 29): {
        "name": "Illusion Generation",
        "kind": "combat",
        "function": IllusionGeneration,
    },
    range(29, 31): {
        "name": "Information Eradication",
        "kind": "combat",
        "function": InformationEradication,
    },
    range(31, 33): {"name": "Intuition", "kind": "combat", "function": Intuition},
    range(33, 35): {
        "name": "Knowledge Transmission",
        "kind": "combat",
        "function": KnowledgeTransmission,
    },
    range(35, 36): {"name": "Levitation", "kind": "combat", "function": Levitation},
    range(36, 37): {"name": "Life Leech", "kind": "combat", "function": LifeLeech},
    range(37, 38): {
        "name": "Light Wave Manipulation",
        "kind": "combat",
        "function": LightWaveManipulation,
    },
    range(38, 40): {
        "name": "Magnetic Control",
        "kind": "combat",
        "function": MagneticControl,
    },
    range(40, 41): {"name": "Mass Mind", "kind": "combat", "function": MassMind},
    range(41, 43): {
        "name": "Mechanical Sense",
        "kind": "combat",
        "function": MechanicalSense,
    },
    range(43, 44): {
        "name": "Mental Blast",
        "kind": "combat",
        "function": MentalBlast,
    },
    range(44, 45): {
        "name": "Mental Control",
        "kind": "combat",
        "function": MentalControl,
    },
    range(45, 46): {
        "name": "Mental Control Over Physical State",
        "kind": "combat",
        "function": MentalControlOverPhysicalState,
    },
    range(46, 48): {
        "name": "Mental Defencelessness",
        "kind": "defect",
        "function": MentalDefencelessness,
    },
    range(48, 49): {
        "name": "Molecular Disruption",
        "kind": "combat",
        "function": MolecularDistruption,
    },
    range(49, 51): {
        "name": "Molecular Examination",
        "kind": "combat",
        "function": MolecularExamination,
    },
    range(51, 52): {
        "name": "Molecular Phase Transformation",
        "kind": "combat",
        "function": MolecularPhaseTransformation,
    },
    range(52, 53): {
        "name": "Molecular Phase Transmutation",
        "kind": "combat",
        "function": MolecularPhaseTransmutation,
    },
    range(53, 54): {
        "name": "Muscle Manipulation",
        "kind": "combat",
        "function": MuscleManipulation,
    },
    range(54, 55): {
        "name": "Neuronegation",
        "kind": "combat",
        "function": Neuronegation,
    },
    range(55, 56): {"name": "Phase", "kind": "combat", "function": Phase},
    range(56, 58): {
        "name": "Planal Hideaway",
        "kind": "combat",
        "function": PlanalHideaway,
    },
    range(58, 60): {
        "name": "Planal Holdaway",
        "kind": "combat",
        "function": PlanalHoldaway,
    },
    range(60, 62): {
        "name": "Polar Disruption",
        "kind": "defect",
        "function": PolarDisruption,
    },
    range(62, 64): {
        "name": "Power Drain",
        "kind": "combat",
        "function": PowerDrain,
    },
    range(64, 66): {
        "name": "Precognition",
        "kind": "combat",
        "function": Precognition,
    },
    range(66, 67): {
        "name": "Projected Sense",
        "kind": "combat",
        "function": ProjectedSense,
    },
    range(67, 68): {
        "name": "Protection Shell",
        "kind": "combat",
        "function": ProtectionShell,
    },
    range(68, 69): {
        "name": "Psionic Defence",
        "kind": "combat",
        "function": PsionicDefence,
    },
    range(69, 70): {"name": "Purify", "kind": "combat", "function": Purify},
    range(70, 72): {
        "name": "Pyrokinesis",
        "kind": "combat",
        "function": Pyrokinesis,
    },
    range(72, 74): {
        "name": "Repulsion Field Generation",
        "kind": "combat",
        "function": RepulsionFieldGeneration,
    },
    range(74, 76): {
        "name": "Restoration",
        "kind": "combat",
        "function": Restoration,
    },
    range(76, 78): {
        "name": "Sensory Deprivation",
        "kind": "combat",
        "function": SensoryDeprivation,
    },
    range(78, 79): {
        "name": "Sociability Field Generation",
        "kind": "combat",
        "function": SociabilityFieldGeneration,
    },
    range(79, 81): {"name": "Sonar", "kind": "combat", "function": Sonar},
    range(81, 82): {
        "name": "Sonic Attack",
        "kind": "combat",
        "function": SonicAttack,
    },
    range(82, 84): {
        "name": "Sonic Reproduction",
        "kind": "combat",
        "function": SonicReproduction,
    },
    range(84, 85): {"name": "Suggestion", "kind": "combat", "function": Suggestion},
    range(85, 86): {
        "name": "Telekinesis",
        "kind": "combat",
        "function": Telekinesis,
    },
    range(86, 87): {
        "name": "Telekinetic Arm",
        "kind": "combat",
        "function": TelekineticArm,
    },
    range(87, 88): {
        "name": "Telekinetic Flight",
        "kind": "combat",
        "function": TelekineticFlight,
    },
    range(88, 89): {"name": "Telempathy", "kind": "combat", "function": Telempathy},
    range(89, 90): {"name": "Teleport", "kind": "combat", "function": Teleport},
    range(90, 91): {
        "name": "Thought Imitation",
        "kind": "combat",
        "function": ThoughtImitation,
    },
    range(91, 92): {"name": "Time Stop", "kind": "combat", "function": TimeStop},
    range(92, 94): {"name": "Time Tell", "kind": "combat", "function": TimeTell},
    range(94, 95): {
        "name": "Total Recuperation",
        "kind": "combat",
        "function": TotalRecuperation,
    },
    range(95, 96): {
        "name": "Ventriloquism",
        "kind": "combat",
        "function": Ventriloquism,
    },
    range(96, 98): {
        "name": "Weapons Discharging",
        "kind": "defect",
        "function": WeaponsDischarging,
    },
    range(98, 100): {
        "name": "Weather Tell",
        "kind": "combat",
        "function": WeatherTell,
    },
    range(100, 101): {
        "name": "Ref's Own Table",
        "kind": "",
        "function": ROT_creator,
    },
    "name": "Mental Mutations",
    "number": 58.1,
    "die_roll": "1d100",
}
